rails_binding_ip = "0.0.0.0"
rails_port = 3000

database_name = "ruby-rails-sample_production"
database_username = "ruby-rails-sample"

# It's up to the end user to set a password for their database, we
# don't want to assume a default that can lead to insecure database
# servers running in the wild.
database_password = ""

# If this is false, then we use the value of database_host in the
# database.yml, otherwise we're going to attempt to find the IP for
# the postgresql server in the "postgresql.default" service group
# (hard coded for now, :sadpanda:)
database_discover = true

# A "safe" fallback is using localhost - we recommend this only be
# used for testing purposes, and instead run a postgresql service that
# can be discovered using gossip
database_host = "localhost"

# It's highly unlikely anyone would want to change this from the
# default, right? but it's configurable. Just in case.
database_port = 5432
